### ISSUE TITLE
?

### ISSUE THREAD

**Issue by BogdanMakarchuk** [thebigsmileXD/gameapi#1]
how to use varion.yml

**Comment by inxomnyaa** [comment]
https://poggit.github.io/support/virion.html

**Comment by BogdanMakarchuk** [comment]
but how to run the plugin with varion.yml?

**Comment by inxomnyaa** [comment]
Next time please google before asking

**Comment by inxomnyaa** [comment]
Must i resend? https://poggit.github.io/support/virion.html 

>> Introduction
Libraries are great in software development, but when multiple plugins use the same library, since they are executing in the same PHP runtime, the wrong version of the library may be used. The Virion framework aims to resolve this problem by shading the classes.

>> Virions are expected to be used by plugins, or by other virions. In this documentation, “virion user” refers to plugins/virions using a virion.

**Comment by inxomnyaa** [comment]
Oh btw, learn to read: V_**i**_rion
