### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by BlueWhaleYT** [thebigsmileXD/gameapi#9]
Hi, although it is a virion.I couldn't figure out this.How to setup a game as this virion said **gameapi**.Is there a tutorial for setting up a example game by using this virion.?
I knew there are some example games with this.Especially BedWars,but how to setup.?

**Comment by inxomnyaa** [comment]
## Here is a heads-up for new users (Example for Spleef)
1. Download DEVirion and DevTools and put it into /plugins
2. Start and stop server to create /virions folder (next to PocketMine.phar, similar to /plugins)
3. Download virions
   1. Download the latest virion of gameapi from Poggit and put it into the /virions folder
   2. Since gameapi depends on apibossbar, also download this virion from Poggit
   3. Alternatively you can go to the PoggitCI repo of Spleef (https://poggit.pmmp.io/ci/thebigsmileXD/Spleef/~), click the latest "Dev" string, it will open an UI where you see "Virions used", you can download them directly from there
4. Download Spleef source code and put it in /plugins
   1. Structure must be /plugins/Spleef/plugin.yml
5. Start the server and try if it works
   1. You might need to put `softdepend: ["DevTools"]` into plugin.yml if things crash

Hope this helps to get you started 💜

**Comment by HixXNetwork** [comment]
its so simple
